In [1]:
from typing import List
import numpy
import numpy.random as random

In [2]:
# because python doesn't have type Vector, we create our own, it translates to just a list of floats
# we can perform addition, multiplication or whatever else on vectors, but they happen componentwise, i.e. to the whole
# [1,2] + [2, 1] = [3, 3]
# whatever you do, they have to be the same length
Vector = List[float]

# such as height_weight_age = [70, 170, 40]
#         grades = [95, 80,75,62]

In [3]:
# adding two vectors together

def add(v: Vector, w: Vector) -> Vector:
    """Adds corresponding elements"""
    assert len(v) == len(w), 'Vectors must be of same length'
    return [v_i + w_i for v_i, w_i in zip(v, w)]

In [4]:
# create random arrays/vectors with whatever size and shape/parameters
size = 10
vector1 = random.randint(0, 10, size=(size))
vector2 = random.randint(0, 10, size=(size))
vector3 = random.randint(0, 10, size=(size))

In [5]:
vector1

array([7, 7, 6, 4, 9, 0, 4, 5, 5, 8])

In [6]:
vector2

array([9, 6, 0, 3, 9, 2, 7, 6, 5, 8])

In [7]:
vector3

array([4, 3, 5, 1, 7, 1, 7, 3, 6, 5])

In [8]:
add(vector1, vector2)

[16, 13, 6, 7, 18, 2, 11, 11, 10, 16]

In [9]:
def subtract(v: Vector, w: Vector) -> Vector:
    """Subtracts corresponding elements"""
    assert len(v) == len(w), 'Vectors must be of same length'
    return[v_i - w_i for v_i, w_i in zip(v, w)]

In [10]:
subtract(vector1, vector2)

[-2, 1, 6, 1, 0, -2, -3, -1, 0, 0]

In [11]:
def vector_sum(vectors: List[Vector]) -> Vector:
    """Sums all corresponding elements"""
    #Check that vectors is not empty
    assert vectors, "No vectors provided!"
    
    #Check that the vectors are all the same size
    num_elements = len(vectors[0])
    assert all(len(v) == num_elements for v in vectors), "Different Sizes"
    
    #The i-th element of the result is the sum of every vector[i]
    return [sum(vector[i] for vector in vectors)
            for i in range(num_elements)]
assert vector_sum([[1,2],[3,4],[5,6], [7,8]]) == [16,20]

In [12]:
vector_sum([vector1, vector2])

[16, 13, 6, 7, 18, 2, 11, 11, 10, 16]

In [13]:
def vector_multiply(c: float, v:Vector) -> Vector:
    """Multiplies every element in a vector by c i.e user input"""
    return [c * v_i for v_i in v]

In [14]:
c = 2
vector = vector1

print(vector1)
print(vector2)
print(vector3)
print(vector_multiply(c, vector))

[7 7 6 4 9 0 4 5 5 8]
[9 6 0 3 9 2 7 6 5 8]
[4 3 5 1 7 1 7 3 6 5]
[14, 14, 12, 8, 18, 0, 8, 10, 10, 16]


In [15]:
def vector_mean(*vectors: List[Vector]) -> Vector:
    """ Computes the element-wise average"""
    
    # number of vectors to average by
    n = len(*vectors)
    return vector_multiply(1/n, vector_sum(*vectors))

In [16]:
#however many vectors you give it, it will do the element-wise average of all of them.
vector_mean([vector1, vector2, vector3])

[6.666666666666666,
 5.333333333333333,
 3.6666666666666665,
 2.6666666666666665,
 8.333333333333332,
 1.0,
 6.0,
 4.666666666666666,
 5.333333333333333,
 7.0]

In [ ]:
# dot product dot() is the sum of their componentwise products
# first multiply the vectors elementwise, then add each element together
# i.e. [1,2,3], [4,5,6] == 32 because 1*4 + 2*5 + 3*6 == 32
