In [73]:
from typing import List
import numpy as np
import numpy.random as random

In [2]:
# because python doesn't have type Vector, we create our own, it translates to just a list of floats
# we can perform addition, multiplication or whatever else on vectors, but they happen componentwise, i.e. to the whole
# [1,2] + [2, 1] = [3, 3]
# whatever you do, they have to be the same length
Vector = List[float]

# such as height_weight_age = [70, 170, 40]
#         grades = [95, 80,75,62]

In [3]:
# adding two vectors together

def add(v: Vector, w: Vector) -> Vector:
    """Adds corresponding elements"""
    assert len(v) == len(w), 'Vectors must be of same length'
    return [v_i + w_i for v_i, w_i in zip(v, w)]

In [4]:
# create random arrays/vectors with whatever size and shape/parameters
size = 10
vector1 = random.randint(0, 10, size=(size))
vector2 = random.randint(0, 10, size=(size))
vector3 = random.randint(0, 10, size=(size))

In [5]:
vector1

array([6, 3, 7, 5, 5, 0, 4, 2, 7, 5])

In [6]:
vector2

array([5, 6, 2, 9, 9, 1, 4, 4, 3, 1])

In [7]:
vector3

array([9, 6, 2, 7, 8, 9, 7, 3, 6, 3])

In [8]:
add(vector1, vector2)

[11, 9, 9, 14, 14, 1, 8, 6, 10, 6]

In [9]:
def subtract(v: Vector, w: Vector) -> Vector:
    """Subtracts corresponding elements"""
    assert len(v) == len(w), 'Vectors must be of same length'
    return[v_i - w_i for v_i, w_i in zip(v, w)]

In [10]:
subtract(vector1, vector2)

[1, -3, 5, -4, -4, -1, 0, -2, 4, 4]

In [11]:
def vector_sum(vectors: List[Vector]) -> Vector:
    """Sums all corresponding elements"""
    #Check that vectors is not empty
    assert vectors, "No vectors provided!"
    
    #Check that the vectors are all the same size
    num_elements = len(vectors[0])
    assert all(len(v) == num_elements for v in vectors), "Different Sizes"
    
    #The i-th element of the result is the sum of every vector[i]
    return [sum(vector[i] for vector in vectors)
            for i in range(num_elements)]
assert vector_sum([[1,2],[3,4],[5,6], [7,8]]) == [16,20]

In [12]:
vector_sum([vector1, vector2])

[11, 9, 9, 14, 14, 1, 8, 6, 10, 6]

In [13]:
def vector_multiply(c: float, v:Vector) -> Vector:
    """Multiplies every element in a vector by c i.e user input"""
    return [c * v_i for v_i in v]

In [14]:
c = 2
vector = vector1

print(vector1)
print(vector2)
print(vector3)
print(vector_multiply(c, vector))

[6 3 7 5 5 0 4 2 7 5]
[5 6 2 9 9 1 4 4 3 1]
[9 6 2 7 8 9 7 3 6 3]
[12, 6, 14, 10, 10, 0, 8, 4, 14, 10]


In [15]:
def vector_mean(*vectors: List[Vector]) -> Vector:
    """ Computes the element-wise average"""
    
    # number of vectors to average by
    n = len(*vectors)
    return vector_multiply(1/n, vector_sum(*vectors))

In [16]:
#however many vectors you give it, it will do the element-wise average of all of them.
vector_mean([vector1, vector2, vector3])

[6.666666666666666,
 5.0,
 3.6666666666666665,
 7.0,
 7.333333333333333,
 3.333333333333333,
 5.0,
 3.0,
 5.333333333333333,
 3.0]

In [22]:
# dot product dot() is the sum of their componentwise products
# first multiply the vectors elementwise, then add each element together
# i.e. [1,2,3], [4,5,6] == 32 because 1*4 + 2*5 + 3*6 == 32

def dot(v: Vector, w: Vector) -> Vector:
    return sum(v_i* w_i for v_i, w_i in zip(v, w))
assert dot([1,2,3], [4,5,6]) == 32  # or 1*4 + 2*5 + 3*6

In [23]:
dot(vector1, vector2)

202

In [25]:
def sum_of_squares(v: Vector) -> float:
    """returns the sum of the squares of each element in a vector"""
    return dot(v,v)
assert sum_of_squares([1,2,3]) == 14 # or 1*1 + 2*2 + 3*3

sum_of_squares(vector1)

238

In [39]:
# we can compute magnitude (or length) with this
import math

def magnitude(v: Vector) -> float:
    return math.sqrt(sum_of_squares(v))
assert magnitude([3,4]) == 5
assert magnitude([4,4,4,4]) == 8
magnitude(vector1)

15.427248620541512

In [41]:
# how to compute the distance between two or more vectors
# square root((v_1 - w_1)^2 + (v_2 - w_2)^2 + etc)

def squared_distance(v: Vector, w: Vector) -> float:
    """Computes (v_1 - w_1) ** 2 + (v_2 - w_2) ** 2 + etc"""
    return sum_of_squares(subtract(v, w))
assert squared_distance([3,4,5], [2,3,4]) == 3
squared_distance(vector1, vector2)

104

In [42]:
def distance(v: Vector, w: Vector) -> Vector:
    return math.sqrt(squared_distance(v,w))
distance(vector1, vector2)

10.198039027185569

**Matrices**

In [43]:
Matrix = List[List[float]]

In [44]:
A = [[1,2,3], #2 rows, 3 columns
     [4,5,6]]
B = [[1,2],   #3 rows, 2 columns
     [3,4], 
     [5,6]]

In [45]:
from typing import Tuple
def shape(A: Matrix) -> Tuple[int, int]:
    """Returns (# rows A, # columns A)"""
    num_rows = len(A)
    num_columns = len(A[0]) if A else 0
    return num_rows, num_columns
    

In [48]:
shape(B)

(3, 2)

In [50]:
# for n rows and k columns we can get 
# the vector of each row length k  and
# the vector of each column length n

def get_row(A, i):
    return A[i]
def get_column(A, j):
    return [A_i[j]
            for A_i in A]

In [52]:
get_row(A, 1)

[3, 4]

In [55]:
get_column(B, 1)

[2, 4, 6]

In [56]:
def make_matrix(num_rows, num_columns, entry):
    """Creates a matrix of entered number of rows * number of columns with the inputted sequence you specify"""
    return [[entry(i,j)
            for j in range(num_columns)]
           for i in range(num_rows)]

In [80]:
make_matrix(10, 10, lambda i, j: random.randint(0, 2))

[[1, 0, 1, 1, 1, 1, 1, 1, 0, 1],
 [0, 1, 0, 0, 0, 1, 0, 1, 1, 1],
 [1, 1, 1, 1, 0, 0, 0, 0, 1, 0],
 [1, 1, 1, 1, 1, 0, 1, 1, 0, 0],
 [0, 1, 0, 1, 1, 0, 0, 0, 0, 1],
 [0, 1, 0, 1, 0, 0, 1, 1, 0, 1],
 [0, 1, 0, 0, 1, 1, 1, 1, 1, 1],
 [0, 1, 1, 1, 0, 1, 0, 1, 0, 0],
 [1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 0]]

In [135]:
# or use this
random.randint(0, 2, size=(10, 10))

array([[1, 0, 1, 1, 0, 0, 1, 0, 0, 1],
       [0, 1, 1, 1, 0, 0, 1, 1, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 1, 0],
       [1, 1, 0, 0, 0, 1, 1, 1, 1, 0],
       [1, 1, 0, 1, 0, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 0, 1, 1, 0, 1, 0],
       [0, 0, 1, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 0, 1],
       [1, 0, 1, 1, 0, 0, 1, 0, 1, 0],
       [1, 1, 0, 1, 1, 1, 1, 0, 1, 1]])

In [150]:
ages = random.randint(18, 100, size=(100, 1))
ages

array([[72],
       [85],
       [53],
       [81],
       [99],
       [86],
       [92],
       [19],
       [62],
       [73],
       [86],
       [39],
       [95],
       [59],
       [28],
       [82],
       [83],
       [88],
       [42],
       [43],
       [75],
       [23],
       [30],
       [18],
       [45],
       [47],
       [95],
       [31],
       [24],
       [22],
       [46],
       [50],
       [49],
       [60],
       [51],
       [47],
       [47],
       [52],
       [91],
       [24],
       [85],
       [80],
       [22],
       [71],
       [58],
       [55],
       [55],
       [31],
       [52],
       [46],
       [41],
       [86],
       [52],
       [21],
       [18],
       [90],
       [47],
       [47],
       [22],
       [77],
       [95],
       [66],
       [20],
       [71],
       [23],
       [63],
       [40],
       [40],
       [85],
       [98],
       [23],
       [53],
       [38],
       [19],
       [70],
       [20],
       [53],

In [151]:
weights = random.randint(100, 200, size=(100, 1))
ages = np.append(ages, weights, axis =1)
# https://numpy.org/devdocs/reference/generated/numpy.append.html
ages

array([[ 72, 102],
       [ 85, 108],
       [ 53, 101],
       [ 81, 123],
       [ 99, 160],
       [ 86, 133],
       [ 92, 139],
       [ 19, 158],
       [ 62, 124],
       [ 73, 139],
       [ 86, 154],
       [ 39, 126],
       [ 95, 161],
       [ 59, 103],
       [ 28, 171],
       [ 82, 121],
       [ 83, 169],
       [ 88, 163],
       [ 42, 192],
       [ 43, 196],
       [ 75, 152],
       [ 23, 133],
       [ 30, 171],
       [ 18, 114],
       [ 45, 124],
       [ 47, 115],
       [ 95, 131],
       [ 31, 125],
       [ 24, 117],
       [ 22, 188],
       [ 46, 147],
       [ 50, 157],
       [ 49, 193],
       [ 60, 124],
       [ 51, 140],
       [ 47, 124],
       [ 47, 107],
       [ 52, 111],
       [ 91, 154],
       [ 24, 145],
       [ 85, 103],
       [ 80, 141],
       [ 22, 143],
       [ 71, 192],
       [ 58, 158],
       [ 55, 192],
       [ 55, 114],
       [ 31, 183],
       [ 52, 116],
       [ 46, 129],
       [ 41, 178],
       [ 86, 164],
       [ 52,

In [152]:
heights = random.randint(55, 80, size=(100, 1))
ages = np.append(ages, heights, axis =1)
ages

array([[ 72, 102,  69],
       [ 85, 108,  72],
       [ 53, 101,  69],
       [ 81, 123,  72],
       [ 99, 160,  79],
       [ 86, 133,  74],
       [ 92, 139,  72],
       [ 19, 158,  79],
       [ 62, 124,  67],
       [ 73, 139,  76],
       [ 86, 154,  62],
       [ 39, 126,  58],
       [ 95, 161,  56],
       [ 59, 103,  73],
       [ 28, 171,  60],
       [ 82, 121,  73],
       [ 83, 169,  75],
       [ 88, 163,  79],
       [ 42, 192,  71],
       [ 43, 196,  59],
       [ 75, 152,  62],
       [ 23, 133,  57],
       [ 30, 171,  76],
       [ 18, 114,  61],
       [ 45, 124,  67],
       [ 47, 115,  72],
       [ 95, 131,  55],
       [ 31, 125,  78],
       [ 24, 117,  77],
       [ 22, 188,  65],
       [ 46, 147,  59],
       [ 50, 157,  67],
       [ 49, 193,  55],
       [ 60, 124,  57],
       [ 51, 140,  68],
       [ 47, 124,  59],
       [ 47, 107,  72],
       [ 52, 111,  69],
       [ 91, 154,  65],
       [ 24, 145,  60],
       [ 85, 103,  75],
       [ 80, 141

In [169]:
# how to get the <0th> row 
ages[0]

array([ 72, 102,  69])

In [171]:
# how to get the column or <0th> axis/indice
# https://stackoverflow.com/questions/4455076/how-to-access-the-ith-column-of-a-numpy-multidimensional-array
ages[:,[0]]

array([[72],
       [85],
       [53],
       [81],
       [99],
       [86],
       [92],
       [19],
       [62],
       [73],
       [86],
       [39],
       [95],
       [59],
       [28],
       [82],
       [83],
       [88],
       [42],
       [43],
       [75],
       [23],
       [30],
       [18],
       [45],
       [47],
       [95],
       [31],
       [24],
       [22],
       [46],
       [50],
       [49],
       [60],
       [51],
       [47],
       [47],
       [52],
       [91],
       [24],
       [85],
       [80],
       [22],
       [71],
       [58],
       [55],
       [55],
       [31],
       [52],
       [46],
       [41],
       [86],
       [52],
       [21],
       [18],
       [90],
       [47],
       [47],
       [22],
       [77],
       [95],
       [66],
       [20],
       [71],
       [23],
       [63],
       [40],
       [40],
       [85],
       [98],
       [23],
       [53],
       [38],
       [19],
       [70],
       [20],
       [53],

In [177]:
assert ages[0][0] == 72, 'This lookup is incorrect'